[tool.black]
line-length = 120

[tool.ruff]
# The same as black
line-length = 120

select = [
    # pyflakes
    "F",
    # pycodestyle
    "E", "W",
    # isort
    "I",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    #flake8-pie
    "PIE",
    #flake8-print
    "T20",
    # flake8-quotes
    "Q",
    # flake8-simplify
    "SIM",
    # tidy imports
    "TID",
    # eradicate
    "ERA",
    # pandas-vet
    "PD",
    # pylint
    "PLE", "PLR", "PLW",
]

unfixable = ['ERA001', "E712"]

ignore = [
    # get-attr-with-constant: SQL-Alchemy Row attributes need to be obtained with 'getattr', since they aren't constant.
    "B009",
    # line-too-long: Some lines need to be long, since correspond to file names.
    "E501",
    # Use `.merge` method instead of `pd.merge` function: pd.merge form is even more readble tha .merge
    "PD015"
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.9.
target-version = "py39"

[tool.ruff.pylint]
max-args = 8
