version: '3.9'

services:
  analytics:
    build: 
      context: ./analytics
      dockerfile: apifast.Dockerfile
    container_name: analytics
    ports:
      - ${ANALYTICS_CONTAINER_PORT}:${ANALYTICS_HOST_PORT}
    volumes:
      - ./analytics:/analytics
    environment:
      ANALYTICS_HOST_NAME: ${ANALYTICS_HOST_NAME}
      ANALYTICS_CONTAINER_PORT: ${ANALYTICS_CONTAINER_PORT}
      ANALYTICS_HOST_PORT: ${ANALYTICS_HOST_PORT}
      FIREBASE_ACCESS_KEYS: ${FIREBASE_ACCESS_KEYS}

  backend:
    build: 
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: backend
    ports:
      - ${BACKEND_CONTAINER_PORT}:${BACKEND_HOST_PORT}
    volumes:
      - ./backend:/backend
    environment:
      BACKEND_HOST_NAME: ${BACKEND_HOST_NAME}
      BACKEND_CONTAINER_PORT: ${BACKEND_CONTAINER_PORT}
      BACKEND_HOST_PORT: ${BACKEND_HOST_PORT}
      MONGODB_URL: ${MONGODB_URL}