version: '3.7'

services:
  analytics:
    build: 
      context: ./analytics
      dockerfile: fastapi.Dockerfile
    container_name: analytics
    ports:
      - ${ANALYTICS_CONTAINER_PORT}:${ANALYTICS_HOST_PORT}
    volumes:
      - ./analytics:/analytics

  mongo_db:
    image: mongo:5.0
    restart: always
    container_name: mongo_db
    ports:
      -  ${MONGO_CONTAINER_PORT}:${MONGO_HOST_PORT}
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    logging:
      driver: none

  backend:
    build: 
      context: ./backend
      dockerfile: node.Dockerfile
    container_name: backend 
    environment:
      MONGO_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_HOSTNAME: "${MONGO_HOSTNAME}"
      MONGO_HOST_PORT: "${MONGO_HOST_PORT}"
      MONGO_DATASET: "${MONGO_DATASET}"
      MONGODB_URL: "${MONGODB_URL}"
    ports:
      - ${NODE_CONTAINER_PORT}:${NODE_HOST_PORT}
    command: npm run dev
    volumes:
      - ./backend:/src
      - nodemodules:/src/node_modules
    depends_on:
      - mongo_db

volumes:
  nodemodules: {}
